/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bulb(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/object/light.glb')
  return (
    <group ref={group} {...props}>
      <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.1, 0.1, 0.1]} position={[...props.position]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ampoule_1.geometry}
          material={materials.wire_225143087}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ampoule_2.geometry}
          material={materials.wire_228184153}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/object/light.glb')