/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/models/object/house_1.glb')
  return (
    <group ref={group} {...props}>
      <group position={[...props.position]} scale={[0.07, 0.11, 0.11]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert_1.geometry}
          material={materials.Edges}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert_2.geometry}
          material={materials.Walls}
        />
        <mesh castShadow receiveShadow geometry={nodes.Vert_3.geometry} material={materials.Roof} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert_4.geometry}
          material={nodes.Vert_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert_5.geometry}
          material={nodes.Vert_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert_6.geometry}
          material={materials.Floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert_7.geometry}
          material={nodes.Vert_7.material}
        />
      </group>
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL +'/models/object/house_1.glb')