/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Match(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/object/diem.glb')
  return (
    <group ref={group} {...props}>
      <group 
        position={[...props.position]}
        rotation={[Math.PI / 2, 0.01, -Math.PI]}
        scale={[0.02, 0.02, 0.02]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Matchstick_1.geometry}
          material={materials['Default OBJ']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Matchstick_2.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/object/diem.glb')