/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Rock(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL +'/models/object/rock.glb')
  return (
    <group ref={group} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rock_1.geometry}
        material={materials.Rock_1}
        position={[...props.position]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.015, 0.015, 0.015]}
      />
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL +'/models/object/rock.glb')